# Use the base image that has ros and pytorch pre-installed
FROM dustynv/ros:jazzy-desktop-r36.4.0-cu128-24.04

# fix the apt-get update error by adding the ROS repository
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys F42ED6FBAB17C654

RUN apt-get update && apt-get install -y \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-tools \
    gstreamer1.0-libav \
    gstreamer1.0-rtsp \
    && rm -rf /var/lib/apt/lists/* \
    && echo 'source /opt/ros/jazzy/setup.bash' >> ~/.bashrc

COPY . /root/sys-arch-2026

WORKDIR /root/sys-arch-2026

RUN source /opt/ros/jazzy/setup.bash && colcon build --packages-up-to vision

# RUN colcon build
# RUN echo "source /opt/ros/jazzy/setup.bash" >> ~/.bashrc
