FROM ultralytics/ultralytics:latest-jetson-jetpack6

# Set the working directory (replacing the manual cd)
WORKDIR /root/sys-arch-2026

# Install ROS 2 Humble and necessary packages
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8
RUN apt update \
	&& apt install -y locales curl software-properties-common \
	&& locale-gen en_US en_US.UTF-8 \
	&& update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 \
	&& add-apt-repository universe \
	&& ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') \
	&& curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo ${UBUNTU_CODENAME:-${VERSION_CODENAME}})_all.deb" \
	&& dpkg -i /tmp/ros2-apt-source.deb \
	&& apt update \
	&& apt install -y ros-humble-desktop \
	&& rm -rf /var/lib/apt/lists/* /tmp/ros2-apt-source.deb