# Use the base image that has ros and pytorch pre-installed
FROM everything:l4t-r36.4.7

RUN apt update && apt install -y \
    ros-jazzy-rosbridge-suite 

RUN apt-get update && apt-get install -y \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-tools \
    gstreamer1.0-libav \
    gstreamer1.0-rtsp \
    && rm -rf /var/lib/apt/lists/*

# COPY ~/sys-arch-2026 /root/sys-arch-2026

WORKDIR /root/sys-arch-2026

# RUN colcon build
# RUN echo "source /opt/ros/jazzy/setup.bash" >> ~/.bashrc