#ifndef SIMPLE_JOYSTICK_CONTROLLER__VISIBILITY_CONTROL_H_
#define SIMPLE_JOYSTICK_CONTROLLER__VISIBILITY_CONTROL_H_
#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define SIMPLE_JOYSTICK_CONTROLLER_EXPORT __attribute__ ((dllexport))
    #define SIMPLE_JOYSTICK_CONTROLLER_IMPORT __attribute__ ((dllimport))
  #else
    #define SIMPLE_JOYSTICK_CONTROLLER_EXPORT __declspec(dllexport)
    #define SIMPLE_JOYSTICK_CONTROLLER_IMPORT __declspec(dllimport)
  #endif
  #ifdef SIMPLE_JOYSTICK_CONTROLLER_BUILDING_LIBRARY
    #define SIMPLE_JOYSTICK_CONTROLLER_PUBLIC SIMPLE_JOYSTICK_CONTROLLER_EXPORT
  #else
    #define SIMPLE_JOYSTICK_CONTROLLER_PUBLIC SIMPLE_JOYSTICK_CONTROLLER_IMPORT
  #endif
  #define SIMPLE_JOYSTICK_CONTROLLER_PUBLIC_TYPE SIMPLE_JOYSTICK_CONTROLLER_PUBLIC
  #define SIMPLE_JOYSTICK_CONTROLLER_LOCAL
#else
  #define SIMPLE_JOYSTICK_CONTROLLER_EXPORT __attribute__ ((visibility("default")))
  #define SIMPLE_JOYSTICK_CONTROLLER_IMPORT
  #if __GNUC__ >= 4
    #define SIMPLE_JOYSTICK_CONTROLLER_PUBLIC __attribute__ ((visibility("default")))
    #define SIMPLE_JOYSTICK_CONTROLLER_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define SIMPLE_JOYSTICK_CONTROLLER_PUBLIC
    #define SIMPLE_JOYSTICK_CONTROLLER_LOCAL
  #endif
  #define SIMPLE_JOYSTICK_CONTROLLER_PUBLIC_TYPE
#endif
#endif  // SIMPLE_JOYSTICK_CONTROLLER__VISIBILITY_CONTROL_H_
// Generated 14-May-2026 23:43:01
 