bt_action_server:
  ros__parameters:
    bt_server_name: "mission_manager_node"
    action_name: "bt_action_server" # Optional (defaults to `bt_action_server`)
    tick_frequency: 100 # Optional (defaults to 100 Hz)
    groot2_port: 1667 # Optional (defaults to 1667)
    ros_plugins_timeout: 1000  # Optional (defaults 1000 ms)
    
    # plugins:
    #   - behaviortree_cpp/bt_plugins
    mission_path: "Trial Mission File.xml"
    
    behavior_trees:
      - behaviortree_ros2/mission_tree_files