# Goal
custom_interfaces/Pose6D tracking_position
custom_interfaces/WaypointMask waypoint_mask
string object
custom_interfaces/Pose6D tolerance
float64 hold_time
float64 timeout
---
# Result
bool success
---
# Feedback