# Goal
custom_interfaces/Pose6D waypoint
custom_interfaces/WaypointMask waypoint_mask
string object
custom_interfaces/Pose6D tolerance
float64 confidence
uint64 hold_time

# Tolerance is set from the blackboard
# float64[6] tolerance
---
# Result
bool success
string found_object
bool reached_waypoint_without_detection
---
# Feedback