# Goal
double[6] tracking_position
bool[6] waypoint_mask
string object
double timeout_sec
# float64 hold_time
# Tolerance is set from the blackboard
# float64[6] tolerance
---
# Result
string result
---
# Feedback
# delta is defined as goal - current position
double[6] delta
double time_in_tolerance