# Goal
string trick                        
float64 duration
bool[6] waypoint_mask               # [1,1,1,1,1,1] = Default to ROS param if unspecified
float64 hold_time
# Tolerance is set from the blackboard
# float64[6] tolerance
---
# Result
bool success
---
# Feedback
float64 remaining duration
float64 time_in_tolerance