# Goal
# drive to world waypoint with a waypoint mask [0 0 1 0 0 0] will cause the robot to surface
#custom_interfaces/Pose6D waypoint
geometry_msgs/Vector3 waypoint_position
geometry_msgs/Vector3 waypoint_orientation
geometry_msgs/Vector3 waypoint_mask_position
geometry_msgs/Vector3 waypoint_mask_orientation
#custom_interfaces/WaypointMask waypoint_mask
geometry_msgs/Vector3 tolerance_position
geometry_msgs/Vector3 tolerance_orientation
#custom_interfaces/Pose6D tolerance
uint64 hold_time
---
# Result
bool success
---
# Feedback