# Goal
float64[] world_waypoint
bool[] waypoint_mask
string object
float64 hold_time
# Tolerance is set from the blackboard
# float64[6] tolerance
---
# Result
string result
---
# Feedback
float64[] delta 
# delta is defined as goal - current position