# Goal
# drive to world waypoint with a waypoint mask [0 0 1 0 0 0] will cause the robot to surface
custom_interfaces/Pose6D waypoint
custom_interfaces/WaypointMask waypoint_mask
custom_interfaces/Pose6D tolerance
float64 hold_time
float64 timeout
---
# Result
bool success
---
# Feedback