#ifndef JOYSTICK_ENABLED_MATLAB_NODE__VISIBILITY_CONTROL_H_
#define JOYSTICK_ENABLED_MATLAB_NODE__VISIBILITY_CONTROL_H_
#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define JOYSTICK_ENABLED_MATLAB_NODE_EXPORT __attribute__ ((dllexport))
    #define JOYSTICK_ENABLED_MATLAB_NODE_IMPORT __attribute__ ((dllimport))
  #else
    #define JOYSTICK_ENABLED_MATLAB_NODE_EXPORT __declspec(dllexport)
    #define JOYSTICK_ENABLED_MATLAB_NODE_IMPORT __declspec(dllimport)
  #endif
  #ifdef JOYSTICK_ENABLED_MATLAB_NODE_BUILDING_LIBRARY
    #define JOYSTICK_ENABLED_MATLAB_NODE_PUBLIC JOYSTICK_ENABLED_MATLAB_NODE_EXPORT
  #else
    #define JOYSTICK_ENABLED_MATLAB_NODE_PUBLIC JOYSTICK_ENABLED_MATLAB_NODE_IMPORT
  #endif
  #define JOYSTICK_ENABLED_MATLAB_NODE_PUBLIC_TYPE JOYSTICK_ENABLED_MATLAB_NODE_PUBLIC
  #define JOYSTICK_ENABLED_MATLAB_NODE_LOCAL
#else
  #define JOYSTICK_ENABLED_MATLAB_NODE_EXPORT __attribute__ ((visibility("default")))
  #define JOYSTICK_ENABLED_MATLAB_NODE_IMPORT
  #if __GNUC__ >= 4
    #define JOYSTICK_ENABLED_MATLAB_NODE_PUBLIC __attribute__ ((visibility("default")))
    #define JOYSTICK_ENABLED_MATLAB_NODE_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define JOYSTICK_ENABLED_MATLAB_NODE_PUBLIC
    #define JOYSTICK_ENABLED_MATLAB_NODE_LOCAL
  #endif
  #define JOYSTICK_ENABLED_MATLAB_NODE_PUBLIC_TYPE
#endif
#endif  // JOYSTICK_ENABLED_MATLAB_NODE__VISIBILITY_CONTROL_H_
// Generated 11-Jul-2026 23:06:38
 