# [-1.0, 1.0] 	Left joystick x axis
float32 x
# [-1.0, 1.0] 	Left joystick y axis
float32 y
# [0.0, 1.0] 	Positive vertical (RT)
float32 rise
# [0.0, 1.0] 	Negative Vertical (LT)
float32 sink
# [-1.0, 1.0] 	Right joystick x axis
float32 yaw
# [-1.0, 1.0] 	Right joystick y axis
float32 pitch
bool cross_button

bool square_button

bool triangle_button

bool circle_button

bool dpad_down

bool dpad_left

bool dpad_up

bool dpad_right

bool bumper_left

bool bumper_right

bool start

bool select

bool joystick_press_left

bool joystick_press_right
